[package]
name = "triggered"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Triggers that allows triggering a one time event in another task/thread"
repository = "https://github.com/faern/triggered"
keywords = ["async", "future"]
categories = ["asynchronous", "concurrency"]
edition = "2018"

[dependencies]

[dev-dependencies]
tokio = { version = "0.2.11", features = ["macros", "rt-threaded"] }
async-std = { version = "1.5.0", features = ["attributes"] }
