[package]
name = "triggered"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tokio = { version = "0.2.11", features = ["macros", "rt-threaded"] }
async-std = { version = "1.5.0", features = ["attributes"] }
